# Generated by Django 5.2 on 2025-05-08 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_centre_remove_customuser_username_customuser_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employeur',
            name='score_risque',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JourConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('controleur', models.ForeignKey(limit_choices_to={'role': 'controleur'}, on_delete=django.db.models.deletion.CASCADE, related_name='jours_conges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
