# Generated by Django 5.2 on 2025-05-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_jourferie_employeur_score_risque_jourconge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeur',
            name='score_risque',
        ),
        migrations.AddField(
            model_name='employeur',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
