# Generated by Django 5.2 on 2025-05-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_employeur_score_risque_employeur_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeur',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
