# Generated by Django 5.2 on 2025-05-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_employeur_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeur',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
