# Generated by Django 5.2 on 2025-05-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_employeur_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jourferie',
            old_name='description',
            new_name='nom',
        ),
    ]
