# Generated by Django 5.2 on 2025-05-08 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_rename_description_jourferie_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('controleur', models.ForeignKey(limit_choices_to={'role': 'controleur'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.employeur')),
            ],
        ),
    ]
