# Generated by Django 5.2 on 2025-05-14 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_planification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('planification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='auth_app.planification')),
            ],
        ),
    ]
