# Generated by Django 5.2 on 2025-05-22 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_report', to='auth_app.planification')),
            ],
            options={
                'verbose_name': 'Rapport de synthèse',
                'verbose_name_plural': 'Rapports de synthèse',
            },
        ),
    ]
