# Generated by Django 5.2 on 2025-05-26 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_summaryreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='superviseur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'superviseur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centres_supervises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='auth_app.centre'),
        ),
    ]
